### ISSUE TITLE
Drain Before Upgrades

### ISSUE THREAD

**Issue by srueg** [kontena/pharos-host-upgrades#39]
Question regarding the drain: Wouldn't it make more sense to drain the node before installing the upgrades instead of just before rebooting? In my experience some of the upgrades restart critical services on a node (i.e. docker, kubelet, etc.) so the node needs to be drained during the upgrade.
Looking forward to your feedback.

**Comment by jnummelin** [comment]
If this is running in the context of Pharos distro, then no. Pharos locks down the essential kube related component (docker, kubelet etc.) versions so those will not be upgraded via host-upgrade daemons.

If running outside of Pharos and not locking the component version, then yes - would make sense to drain before the upgrades.
